// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA21GGxAvdjgWxUpP4qurz3ag2WfbG0O64',
    appId: '1:1046179851893:web:f8125087560fbc6c4f123c',
    messagingSenderId: '1046179851893',
    projectId: 'mydatabase-c4bda',
    authDomain: 'mydatabase-c4bda.firebaseapp.com',
    storageBucket: 'mydatabase-c4bda.firebasestorage.app',
    measurementId: 'G-25N3YFNBJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBElO7mcbC8dVX_ibL2Qp12Z_iF-VLpSUY',
    appId: '1:1046179851893:android:68b6fc27f6d725184f123c',
    messagingSenderId: '1046179851893',
    projectId: 'mydatabase-c4bda',
    storageBucket: 'mydatabase-c4bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADkKXL3wjqCS7pw_vG23P7_rBpNf_3duQ',
    appId: '1:1046179851893:ios:590a46e7aea32b704f123c',
    messagingSenderId: '1046179851893',
    projectId: 'mydatabase-c4bda',
    storageBucket: 'mydatabase-c4bda.firebasestorage.app',
    iosBundleId: 'com.example.myApp2',
  );
}
